# Markdownlint Configuration
# Markdown linting rules for documentation quality
# Referenced by: pre-commit-config.yaml
#
# Documentation: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD001 - Heading levels should only increment by one level at a time
MD001: true

# MD003 - Heading style (consistent, atx, atx_closed, setext, setext_with_atx, setext_with_atx_closed)
MD003:
  style: atx  # Use # style headings

# MD004 - Unordered list style (consistent, asterisk, plus, dash)
MD004:
  style: dash  # Use - for lists

# MD005 - Inconsistent indentation for list items at the same level
MD005: true

# MD007 - Unordered list indentation
MD007:
  indent: 2  # 2 spaces for nested lists

# MD009 - Trailing spaces
MD009:
  br_spaces: 2  # Allow 2 trailing spaces for line breaks
  list_item_empty_lines: false
  strict: false

# MD010 - Hard tabs
MD010:
  code_blocks: false  # Allow tabs in code blocks

# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 2  # Allow up to 2 blank lines

# MD013 - Line length
MD013: false  # Disabled for technical docs with long URLs/commands

# MD022 - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024 - Multiple headings with the same content
MD024:
  siblings_only: true  # Allow same heading in different sections

# MD025 - Multiple top-level headings in the same document
MD025: true

# MD026 - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!。，；：！"  # Disallow these at end of headings

# MD029 - Ordered list item prefix
MD029:
  style: ordered  # Use sequential numbers (1, 2, 3)

# MD030 - Spaces after list markers
MD030:
  ul_single: 1  # 1 space after unordered list marker
  ul_multi: 1
  ol_single: 1  # 1 space after ordered list marker
  ol_multi: 1

# MD031 - Fenced code blocks should be surrounded by blank lines
MD031: true

# MD032 - Lists should be surrounded by blank lines
MD032: true

# MD033 - Inline HTML
MD033:
  allowed_elements: []  # Disallow inline HTML (can add exceptions if needed)

# MD034 - Bare URL used
MD034: false  # Allow bare URLs (common in technical docs)

# MD035 - Horizontal rule style
MD035:
  style: "---"

# MD023 - Headings must start at the beginning of the line
MD023: false  # Allow indented headings in nested contexts

# MD036 - Emphasis used instead of a heading
MD036: false  # Allow bold/italic for emphasis

# MD037 - Spaces inside emphasis markers
MD037: true

# MD038 - Spaces inside code span elements
MD038: true

# MD039 - Spaces inside link text
MD039: true

# MD040 - Fenced code blocks should have a language specified
MD040: false  # Allow code blocks without language

# MD041 - First line in file should be a top-level heading
MD041: false  # Allow frontmatter or other content before heading

# MD042 - No empty links
MD042: true

# MD043 - Required heading structure
MD043: false  # Don't enforce specific heading structure

# MD044 - Proper names should have the correct capitalization
MD044: false  # Allow flexibility in capitalization

# MD045 - Images should have alternate text (alt text)
MD045: true

# MD046 - Code block style
MD046:
  style: fenced  # Use ``` style code blocks

# MD047 - Files should end with a single newline character
MD047: true

# MD048 - Code fence style
MD048:
  style: backtick  # Use ``` not ~~~

# MD049 - Emphasis style should be consistent
MD049:
  style: asterisk  # Use * for emphasis

# MD050 - Strong style should be consistent
MD050:
  style: asterisk  # Use ** for strong

# MD051 - Link fragments should be valid
MD051: true

# MD052 - Reference links and images should use a label that is defined
MD052: true

# MD053 - Link and image reference definitions should be needed
MD053:
  ignored_definitions: []
