# markdownlint-cli2 Configuration
# Markdown linting rules for documentation quality
# Referenced by: .pre-commit-config.yaml
#
# Documentation: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Globs to ignore
globs:
  - "!CHANGELOG.md"
  - "!specs/**"
  - "!.specify/**"
  - "!.gemini/**"
  - "!.claude/**"
  - "!node_modules/**"
  - "!.terraform/**"

# Configuration (all rules enabled by default)
config:
  # MD003 - Heading style
  MD003:
    style: "atx"  # Use # style headings

  # MD004 - Unordered list style
  MD004:
    style: "dash"  # Use - for lists

  # MD007 - Unordered list indentation
  MD007:
    indent: 2  # 2 spaces for nested lists

  # MD013 - Line length
  MD013: false  # Disabled for technical docs with long URLs/commands/examples

  # MD024 - Multiple headings with the same content
  MD024:
    siblings_only: true  # Allow same heading in different sections

  # MD033 - Inline HTML
  MD033:
    allowed_elements: []  # Disallow inline HTML

  # MD034 - Bare URL used
  MD034: false  # Allow bare URLs (common in technical docs)

  # MD023 - Headings must start at the beginning of the line
  MD023: false  # Allow indented headings in nested contexts

  # MD036 - Emphasis used instead of a heading
  MD036: false  # Allow bold/italic for emphasis in technical docs

  # MD040 - Fenced code blocks should have a language specified
  MD040: false  # Allow code blocks without language (generic output examples)

  # MD041 - First line in file should be a top-level heading
  MD041: false  # Allow frontmatter or other content before heading

  # MD044 - Proper names should have the correct capitalization
  MD044: false  # Allow flexibility in capitalization for technical terms

  # MD046 - Code block style
  MD046:
    style: "fenced"  # Use ``` style code blocks
